package INSPIREValidationDSL;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.ILanguageAspect;
import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "da2eac80-1303-47f2-9f08-1138f7e080a2(INSPIREValidationDSL)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "INSPIREValidationDSL";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("da2eac80-1303-47f2-9f08-1138f7e080a2"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "7f3b4ed4-31ea-4ae0-b1d5-ce1be1cef2aa(INSPIREValidationDSL#7094536717254991605)"));
  }
  @Override
  protected <T extends ILanguageAspect> T createAspect(Class<T> aspectClass) {
    if (aspectClass == EditorAspectDescriptor.class) {
      return ((T) new EditorAspectDescriptorBase());
    }
    return super.createAspect(aspectClass);
  }
}
